using EFCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EFCore.Configurations
{
    public class StockConfiguration : IEntityTypeConfiguration<Stock>
    {
        public void Configure(EntityTypeBuilder<Stock> builder)
        {
            #region Seed Stock Data
            
            builder.HasData(
                new Stock { Id = 1, Name = "First Trust Total US Market AlphaDEX ETF", Symbol = "TUSA", Sector = "n/a", Industry = "n/a", Balance = 1967.08 },
                new Stock { Id = 2, Name = "aTyr Pharma, Inc.", Symbol = "LIFE", Sector = "Health Care", Industry = "Biotechnology: Biological Products (No Diagnostic Substances)", Balance = 99345.82 },
                new Stock { Id = 3, Name = "1st Source Corporation", Symbol = "SRCE", Sector = "Finance", Industry = "Major Banks", Balance = 99794.81 },
                new Stock { Id = 4, Name = "BioDelivery Sciences International, Inc.", Symbol = "BDSI", Sector = "Health Care", Industry = "Major Pharmaceuticals", Balance = 72500.85 },
                new Stock { Id = 5, Name = "Summit Therapeutics plc", Symbol = "SMMT", Sector = "Health Care", Industry = "Major Pharmaceuticals", Balance = 23123.77 },
                new Stock { Id = 6, Name = "CYREN Ltd.", Symbol = "CYRN", Sector = "Technology", Industry = "Computer Software: Prepackaged Software", Balance = 95595.26 },
                new Stock { Id = 7, Name = "Evogene Ltd.", Symbol = "EVGN", Sector = "Basic Industries", Industry = "Agricultural Chemicals", Balance = 54470.32 },
                new Stock { Id = 8, Name = "Rio Tinto Plc", Symbol = "RIO", Sector = "Basic Industries", Industry = "Precious Metals", Balance = 44935.81 },
                new Stock { Id = 9, Name = "Avery Dennison Corporation", Symbol = "AVY", Sector = "Consumer Durables", Industry = "Containers/Packaging", Balance = 98873.45 },
                new Stock { Id = 10, Name = "Optibase Ltd.", Symbol = "OBAS", Sector = "Finance", Industry = "Real Estate", Balance = 51308.29 },
                new Stock { Id = 11, Name = "Invesco Municipal Opportunity Trust", Symbol = "VMO", Sector = "n/a", Industry = "n/a", Balance = 4713.91 },
                new Stock { Id = 12, Name = "EVINE Live Inc.", Symbol = "EVLV", Sector = "Consumer Services", Industry = "Catalog/Specialty Distribution", Balance = 89388.61 },
                new Stock { Id = 13, Name = "Exact Sciences Corporation", Symbol = "EXAS", Sector = "Health Care", Industry = "Biotechnology: Commercial Physical & Biological Resarch", Balance = 64653.48 },
                new Stock { Id = 14, Name = "Foot Locker, Inc.", Symbol = "FL", Sector = "Consumer Services", Industry = "Clothing/Shoe/Accessory Stores", Balance = 25532.30 },
                new Stock { Id = 15, Name = "Vuzix Corporation", Symbol = "VUZI", Sector = "Technology", Industry = "Radio And Television Broadcasting And Communications Equipment", Balance = 46424.13 },
                new Stock { Id = 16, Name = "Pyxis Tankers Inc.", Symbol = "PXS", Sector = "Transportation", Industry = "Marine Transportation", Balance = 19062.60 },
                new Stock { Id = 17, Name = "Total System Services, Inc.", Symbol = "TSS", Sector = "Miscellaneous", Industry = "Business Services", Balance = 72709.26 },
                new Stock { Id = 18, Name = "AquaVenture Holdings Limited", Symbol = "WAAS", Sector = "Public Utilities", Industry = "Water Supply", Balance = 38747.51 },
                new Stock { Id = 19, Name = "Hawkins, Inc.", Symbol = "HWKN", Sector = "Consumer Durables", Industry = "Specialty Chemicals", Balance = 79821.97 },
                new Stock { Id = 20, Name = "PennantPark Floating Rate Capital Ltd.", Symbol = "PFLT", Sector = "n/a", Industry = "n/a", Balance = 22480.36 },
                new Stock { Id = 21, Name = "Alliqua BioMedical, Inc.", Symbol = "ALQA", Sector = "Health Care", Industry = "Medical/Dental Instruments", Balance = 64379.20 },
                new Stock { Id = 22, Name = "V.F. Corporation", Symbol = "VFC", Sector = "Consumer Non-Durables", Industry = "Apparel", Balance = 29351.20 },
                new Stock { Id = 23, Name = "Drive Shack Inc.", Symbol = "DS^D", Sector = "n/a", Industry = "n/a", Balance = 78091.15 },
                new Stock { Id = 24, Name = "GDS Holdings Limited", Symbol = "GDS", Sector = "Technology", Industry = "Computer Software: Programming, Data Processing", Balance = 95637.65 },
                new Stock { Id = 25, Name = "Seres Therapeutics, Inc.", Symbol = "MCRB", Sector = "Health Care", Industry = "Major Pharmaceuticals", Balance = 75840.47 },
                new Stock { Id = 26, Name = "South State Corporation", Symbol = "SSB", Sector = "Finance", Industry = "Major Banks", Balance = 57641.58 },
                new Stock { Id = 27, Name = "FelCor Lodging Trust Incorporated", Symbol = "FCH", Sector = "Consumer Services", Industry = "Real Estate Investment Trusts", Balance = 12908.59 },
                new Stock { Id = 28, Name = "Proto Labs, Inc.", Symbol = "PRLB", Sector = "Capital Goods", Industry = "Metal Fabrications", Balance = 52723.69 },
                new Stock { Id = 29, Name = "Crown Crafts, Inc.", Symbol = "CRWS", Sector = "Basic Industries", Industry = "Textiles", Balance = 35791.33 },
                new Stock { Id = 30, Name = "Peak Resorts, Inc.", Symbol = "SKIS", Sector = "Consumer Services", Industry = "Hotels/Resorts", Balance = 23749.58 },
                new Stock { Id = 31, Name = "China Lodging Group, Limited", Symbol = "HTHT", Sector = "Consumer Services", Industry = "Hotels/Resorts", Balance = 51499.77 },
                new Stock { Id = 32, Name = "Big 5 Sporting Goods Corporation", Symbol = "BGFV", Sector = "Consumer Services", Industry = "Other Specialty Stores", Balance = 81785.89 },
                new Stock { Id = 33, Name = "Pennsylvania Real Estate Investment Trust", Symbol = "PEI", Sector = "Consumer Services", Industry = "Real Estate Investment Trusts", Balance = 11477.49 },
                new Stock { Id = 34, Name = "Boot Barn Holdings, Inc.", Symbol = "BOOT", Sector = "Consumer Services", Industry = "Clothing/Shoe/Accessory Stores", Balance = 89203.63 },
                new Stock { Id = 35, Name = "Vaalco Energy Inc", Symbol = "EGY", Sector = "Energy", Industry = "Oil & Gas Production", Balance = 38603.37 },
                new Stock { Id = 36, Name = "Albireo Pharma, Inc.", Symbol = "ALBO", Sector = "Health Care", Industry = "Major Pharmaceuticals", Balance = 5802.40 },
                new Stock { Id = 37, Name = "Tsakos Energy Navigation Ltd", Symbol = "TNP^C", Sector = "n/a", Industry = "n/a", Balance = 10248.78 },
                new Stock { Id = 38, Name = "Western Digital Corporation", Symbol = "WDC", Sector = "Technology", Industry = "Electronic Components", Balance = 64759.14 },
                new Stock { Id = 39, Name = "Vistra Energy Corp.", Symbol = "VST", Sector = "Public Utilities", Industry = "Electric Utilities: Central", Balance = 6498.58 },
                new Stock { Id = 40, Name = "Washington Prime Group Inc.", Symbol = "WPG^H", Sector = "n/a", Industry = "n/a", Balance = 98211.90 },
                new Stock { Id = 41, Name = "Antares Pharma, Inc.", Symbol = "ATRS", Sector = "Health Care", Industry = "Medical/Dental Instruments", Balance = 14916.44 },
                new Stock { Id = 42, Name = "MINDBODY, Inc.", Symbol = "MB", Sector = "Technology", Industry = "EDP Services", Balance = 20345.33 },
                new Stock { Id = 43, Name = "Intel Corporation", Symbol = "INTC", Sector = "Technology", Industry = "Semiconductors", Balance = 48828.24 },
                new Stock { Id = 44, Name = "BlackRock Investment Quality Municipal Trust Inc. (The)", Symbol = "BKN", Sector = "n/a", Industry = "n/a", Balance = 22197.13 },
                new Stock { Id = 45, Name = "Harmony Merger Corp.", Symbol = "HRMNW", Sector = "Public Utilities", Industry = "Oil & Gas Production", Balance = 90814.04 },
                new Stock { Id = 46, Name = "Cellectar Biosciences, Inc.", Symbol = "CLRB", Sector = "Health Care", Industry = "Major Pharmaceuticals", Balance = 5035.78 },
                new Stock { Id = 47, Name = "Park City Group, Inc.", Symbol = "PCYG", Sector = "Technology", Industry = "EDP Services", Balance = 67233.79 },
                new Stock { Id = 48, Name = "Macquarie Infrastructure Company", Symbol = "MIC", Sector = "Energy", Industry = "Oil Refining/Marketing", Balance = 59289.51 },
                new Stock { Id = 49, Name = "MaxLinear, Inc", Symbol = "MXL", Sector = "Technology", Industry = "Semiconductors", Balance = 71891.35 },
                new Stock { Id = 50, Name = "Hugoton Royalty Trust", Symbol = "HGT", Sector = "Energy", Industry = "Oil & Gas Production", Balance = 22161.28 },
                new Stock { Id = 51, Name = "Pathfinder Bancorp, Inc.", Symbol = "PBHC", Sector = "Finance", Industry = "Major Banks", Balance = 83215.21 },
                new Stock { Id = 52, Name = "Leggett & Platt, Incorporated", Symbol = "LEG", Sector = "Consumer Durables", Industry = "Home Furnishings", Balance = 64260.57 },
                new Stock { Id = 53, Name = "Kate Spade & Company", Symbol = "KATE", Sector = "Consumer Non-Durables", Industry = "Apparel", Balance = 63801.89 },
                new Stock { Id = 54, Name = "Protective Life Corporation", Symbol = "PL^E", Sector = "n/a", Industry = "n/a", Balance = 3350.51 },
                new Stock { Id = 55, Name = "Cencosud S.A.", Symbol = "CNCO", Sector = "Consumer Services", Industry = "Department/Specialty Retail Stores", Balance = 7597.96 },
                new Stock { Id = 56, Name = "Magyar Bancorp, Inc.", Symbol = "MGYR", Sector = "Finance", Industry = "Savings Institutions", Balance = 6098.87 },
                new Stock { Id = 57, Name = "DelMar Pharmaceuticals, Inc.", Symbol = "DMPI", Sector = "Health Care", Industry = "Major Pharmaceuticals", Balance = 77505.59 },
                new Stock { Id = 58, Name = "First Trust Small Cap Core AlphaDEX Fund", Symbol = "FYX", Sector = "n/a", Industry = "n/a", Balance = 3428.35 },
                new Stock { Id = 59, Name = "China TechFaith Wireless Communication Technology Limited", Symbol = "CNTF", Sector = "n/a", Industry = "n/a", Balance = 73733.93 },
                new Stock { Id = 60, Name = "Canadian Natural Resources Limited", Symbol = "CNQ", Sector = "Energy", Industry = "Oil & Gas Production", Balance = 51952.18 },
                new Stock { Id = 61, Name = "Glaukos Corporation", Symbol = "GKOS", Sector = "Health Care", Industry = "Medical/Dental Instruments", Balance = 41505.23 },
                new Stock { Id = 62, Name = "Dreyfus Municipal Bond Infrastructure Fund, Inc.", Symbol = "DMB", Sector = "n/a", Industry = "n/a", Balance = 78836.59 },
                new Stock { Id = 63, Name = "Grupo Aeroportuario del Sureste, S.A. de C.V.", Symbol = "ASR", Sector = "Transportation", Industry = "Aerospace", Balance = 31240.14 },
                new Stock { Id = 64, Name = "iRobot Corporation", Symbol = "IRBT", Sector = "Consumer Durables", Industry = "Consumer Electronics/Appliances", Balance = 59982.03 },
                new Stock { Id = 65, Name = "UnitedHealth Group Incorporated", Symbol = "UNH", Sector = "Health Care", Industry = "Medical Specialities", Balance = 62750.65 },
                new Stock { Id = 66, Name = "Sabre Corporation", Symbol = "SABR", Sector = "Technology", Industry = "Computer Software: Programming, Data Processing", Balance = 64337.14 },
                new Stock { Id = 67, Name = "Willamette Valley Vineyards, Inc.", Symbol = "WVVI", Sector = "Consumer Non-Durables", Industry = "Beverages (Production/Distribution)", Balance = 91239.97 },
                new Stock { Id = 68, Name = "ZAGG Inc", Symbol = "ZAGG", Sector = "Consumer Services", Industry = "Other Specialty Stores", Balance = 55349.68 },
                new Stock { Id = 69, Name = "Navios Maritime Partners LP", Symbol = "NMM", Sector = "Transportation", Industry = "Marine Transportation", Balance = 93187.48 },
                new Stock { Id = 70, Name = "Grupo Aeroportuario del Centro Norte S.A.B. de C.V.", Symbol = "OMAB", Sector = "Transportation", Industry = "Aerospace", Balance = 11844.24 },
                new Stock { Id = 71, Name = "Public Storage", Symbol = "PSA^Z", Sector = "n/a", Industry = "n/a", Balance = 87019.61 },
                new Stock { Id = 72, Name = "Blackrock Core Bond Trust", Symbol = "BHK", Sector = "n/a", Industry = "n/a", Balance = 66098.82 },
                new Stock { Id = 73, Name = "The Spectranetics Corporation", Symbol = "SPNC", Sector = "Health Care", Industry = "Biotechnology: Electromedical & Electrotherapeutic Apparatus", Balance = 57311.29 },
                new Stock { Id = 74, Name = "MGM Resorts International", Symbol = "MGM", Sector = "Consumer Services", Industry = "Hotels/Resorts", Balance = 92281.46 },
                new Stock { Id = 75, Name = "Vanguard Short-Term Government ETF", Symbol = "VGSH", Sector = "n/a", Industry = "n/a", Balance = 84788.13 },
                new Stock { Id = 76, Name = "Texas Capital Bancshares, Inc.", Symbol = "TCBIP", Sector = "Finance", Industry = "Major Banks", Balance = 30063.70 },
                new Stock { Id = 77, Name = "J & J Snack Foods Corp.", Symbol = "JJSF", Sector = "Consumer Non-Durables", Industry = "Specialty Foods", Balance = 16803.58 },
                new Stock { Id = 78, Name = "WPP plc", Symbol = "WPPGY", Sector = "Technology", Industry = "Advertising", Balance = 51587.36 },
                new Stock { Id = 79, Name = "Key Technology, Inc.", Symbol = "KTEC", Sector = "Technology", Industry = "Industrial Machinery/Components", Balance = 45519.29 },
                new Stock { Id = 80, Name = "Sophiris Bio, Inc.", Symbol = "SPHS", Sector = "n/a", Industry = "n/a", Balance = 15341.25 },
                new Stock { Id = 81, Name = "PartnerRe Ltd.", Symbol = "PRE^G", Sector = "n/a", Industry = "n/a", Balance = 35990.81 },
                new Stock { Id = 82, Name = "CSI Compressco LP", Symbol = "CCLP", Sector = "Energy", Industry = "Oilfield Services/Equipment", Balance = 88537.06 },
                new Stock { Id = 83, Name = "Criteo S.A.", Symbol = "CRTO", Sector = "Technology", Industry = "Advertising", Balance = 31509.09 },
                new Stock { Id = 84, Name = "Aviragen Therapeutics, Inc.", Symbol = "AVIR", Sector = "Health Care", Industry = "Biotechnology: Biological Products (No Diagnostic Substances)", Balance = 37413.41 },
                new Stock { Id = 85, Name = "State Street Corporation", Symbol = "STT^E", Sector = "n/a", Industry = "n/a", Balance = 28476.53 },
                new Stock { Id = 86, Name = "Old Point Financial Corporation", Symbol = "OPOF", Sector = "Finance", Industry = "Major Banks", Balance = 54783.06 },
                new Stock { Id = 87, Name = "iShares MSCI ACWI ex US Index Fund", Symbol = "ACWX", Sector = "n/a", Industry = "n/a", Balance = 74553.88 },
                new Stock { Id = 88, Name = "Exelixis, Inc.", Symbol = "EXEL", Sector = "Health Care", Industry = "Biotechnology: Commercial Physical & Biological Resarch", Balance = 82628.45 },
                new Stock { Id = 89, Name = "Ternium S.A.", Symbol = "TX", Sector = "Basic Industries", Industry = "Steel/Iron Ore", Balance = 58492.61 },
                new Stock { Id = 90, Name = "CBAK Energy Technology, Inc.", Symbol = "CBAK", Sector = "Miscellaneous", Industry = "Industrial Machinery/Components", Balance = 87167.31 },
                new Stock { Id = 91, Name = "Soligenix, Inc.", Symbol = "SNGX", Sector = "Health Care", Industry = "Major Pharmaceuticals", Balance = 74861.44 },
                new Stock { Id = 92, Name = "Novo Nordisk A/S", Symbol = "NVO", Sector = "Health Care", Industry = "Major Pharmaceuticals", Balance = 34085.30 },
                new Stock { Id = 93, Name = "Uranium Resources, Inc.", Symbol = "URRE", Sector = "Basic Industries", Industry = "Precious Metals", Balance = 90172.30 },
                new Stock { Id = 94, Name = "Second Sight Medical Products, Inc.", Symbol = "EYES", Sector = "n/a", Industry = "n/a", Balance = 43757.61 },
                new Stock { Id = 95, Name = "PhaseRx, Inc.", Symbol = "PZRX", Sector = "Health Care", Industry = "Major Pharmaceuticals", Balance = 82323.93 },
                new Stock { Id = 96, Name = "Pointer Telocation Ltd.", Symbol = "PNTR", Sector = "Technology", Industry = "Radio And Television Broadcasting And Communications Equipment", Balance = 71047.13 },
                new Stock { Id = 97, Name = "AMAG Pharmaceuticals, Inc.", Symbol = "AMAG", Sector = "Health Care", Industry = "Major Pharmaceuticals", Balance = 35785.67 },
                new Stock { Id = 98, Name = "Scorpio Tankers Inc.", Symbol = "SBNA", Sector = "Transportation", Industry = "Marine Transportation", Balance = 31341.64 },
                new Stock { Id = 99, Name = "PowerShares DWA Consumer Staples Momentum Portfolio", Symbol = "PSL", Sector = "n/a", Industry = "n/a", Balance = 2178.93 },
                new Stock { Id = 100, Name = "Assurant, Inc.", Symbol = "AIZ", Sector = "Finance", Industry = "Accident &Health Insurance", Balance = 92176.68 },
                new Stock { Id = 101, Name = "Inogen, Inc", Symbol = "INGN", Sector = "Health Care", Industry = "Industrial Specialties", Balance = 54742.53 },
                new Stock { Id = 102, Name = "Itron, Inc.", Symbol = "ITRI", Sector = "Capital Goods", Industry = "Electrical Products", Balance = 29819.96 },
                new Stock { Id = 103, Name = "A10 Networks, Inc.", Symbol = "ATEN", Sector = "Technology", Industry = "Computer Communications Equipment", Balance = 27661.12 },
                new Stock { Id = 104, Name = "Hunter Maritime Acquisition Corp.", Symbol = "HUNT", Sector = "Transportation", Industry = "Oil Refining/Marketing", Balance = 78015.05 },
                new Stock { Id = 105, Name = "Colony Bankcorp, Inc.", Symbol = "CBAN", Sector = "Finance", Industry = "Major Banks", Balance = 54286.53 },
                new Stock { Id = 106, Name = "C.H. Robinson Worldwide, Inc.", Symbol = "CHRW", Sector = "Transportation", Industry = "Oil Refining/Marketing", Balance = 53985.80 },
                new Stock { Id = 107, Name = "Enova International, Inc.", Symbol = "ENVA", Sector = "Finance", Industry = "Finance: Consumer Services", Balance = 74587.33 },
                new Stock { Id = 108, Name = "QUALCOMM Incorporated", Symbol = "QCOM", Sector = "Technology", Industry = "Radio And Television Broadcasting And Communications Equipment", Balance = 11486.77 },
                new Stock { Id = 109, Name = "Globus Medical, Inc.", Symbol = "GMED", Sector = "Health Care", Industry = "Medical/Dental Instruments", Balance = 62602.78 },
                new Stock { Id = 110, Name = "First Trust Nasdaq Pharmaceuticals ETF", Symbol = "FTXH", Sector = "n/a", Industry = "n/a", Balance = 2535.11 }
            );
            
            #endregion
        }
    }
}