// <auto-generated />
using EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205144807_seedStocksData02")]
    partial class seedStocksData02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.Models.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("EFCore.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("EFCore.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("EFCore.Models.BlogImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlogId")
                        .IsUnique();

                    b.ToTable("BlogImages");
                });

            modelBuilder.Entity("EFCore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("EFCore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EFCore.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EFCore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<long>("OrderNo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EFCore.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EFCore.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1967.0799999999999,
                            Industry = "n/a",
                            Name = "First Trust Total US Market AlphaDEX ETF",
                            Sector = "n/a",
                            Symbol = "TUSA"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 99345.820000000007,
                            Industry = "Biotechnology: Biological Products (No Diagnostic Substances)",
                            Name = "aTyr Pharma, Inc.",
                            Sector = "Health Care",
                            Symbol = "LIFE"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 99794.809999999998,
                            Industry = "Major Banks",
                            Name = "1st Source Corporation",
                            Sector = "Finance",
                            Symbol = "SRCE"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 72500.850000000006,
                            Industry = "Major Pharmaceuticals",
                            Name = "BioDelivery Sciences International, Inc.",
                            Sector = "Health Care",
                            Symbol = "BDSI"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 23123.77,
                            Industry = "Major Pharmaceuticals",
                            Name = "Summit Therapeutics plc",
                            Sector = "Health Care",
                            Symbol = "SMMT"
                        },
                        new
                        {
                            Id = 6,
                            Balance = 95595.259999999995,
                            Industry = "Computer Software: Prepackaged Software",
                            Name = "CYREN Ltd.",
                            Sector = "Technology",
                            Symbol = "CYRN"
                        },
                        new
                        {
                            Id = 7,
                            Balance = 54470.32,
                            Industry = "Agricultural Chemicals",
                            Name = "Evogene Ltd.",
                            Sector = "Basic Industries",
                            Symbol = "EVGN"
                        },
                        new
                        {
                            Id = 8,
                            Balance = 44935.809999999998,
                            Industry = "Precious Metals",
                            Name = "Rio Tinto Plc",
                            Sector = "Basic Industries",
                            Symbol = "RIO"
                        },
                        new
                        {
                            Id = 9,
                            Balance = 98873.449999999997,
                            Industry = "Containers/Packaging",
                            Name = "Avery Dennison Corporation",
                            Sector = "Consumer Durables",
                            Symbol = "AVY"
                        },
                        new
                        {
                            Id = 10,
                            Balance = 51308.290000000001,
                            Industry = "Real Estate",
                            Name = "Optibase Ltd.",
                            Sector = "Finance",
                            Symbol = "OBAS"
                        },
                        new
                        {
                            Id = 11,
                            Balance = 4713.9099999999999,
                            Industry = "n/a",
                            Name = "Invesco Municipal Opportunity Trust",
                            Sector = "n/a",
                            Symbol = "VMO"
                        },
                        new
                        {
                            Id = 12,
                            Balance = 89388.610000000001,
                            Industry = "Catalog/Specialty Distribution",
                            Name = "EVINE Live Inc.",
                            Sector = "Consumer Services",
                            Symbol = "EVLV"
                        },
                        new
                        {
                            Id = 13,
                            Balance = 64653.480000000003,
                            Industry = "Biotechnology: Commercial Physical & Biological Resarch",
                            Name = "Exact Sciences Corporation",
                            Sector = "Health Care",
                            Symbol = "EXAS"
                        },
                        new
                        {
                            Id = 14,
                            Balance = 25532.299999999999,
                            Industry = "Clothing/Shoe/Accessory Stores",
                            Name = "Foot Locker, Inc.",
                            Sector = "Consumer Services",
                            Symbol = "FL"
                        },
                        new
                        {
                            Id = 15,
                            Balance = 46424.129999999997,
                            Industry = "Radio And Television Broadcasting And Communications Equipment",
                            Name = "Vuzix Corporation",
                            Sector = "Technology",
                            Symbol = "VUZI"
                        },
                        new
                        {
                            Id = 16,
                            Balance = 19062.599999999999,
                            Industry = "Marine Transportation",
                            Name = "Pyxis Tankers Inc.",
                            Sector = "Transportation",
                            Symbol = "PXS"
                        },
                        new
                        {
                            Id = 17,
                            Balance = 72709.259999999995,
                            Industry = "Business Services",
                            Name = "Total System Services, Inc.",
                            Sector = "Miscellaneous",
                            Symbol = "TSS"
                        },
                        new
                        {
                            Id = 18,
                            Balance = 38747.510000000002,
                            Industry = "Water Supply",
                            Name = "AquaVenture Holdings Limited",
                            Sector = "Public Utilities",
                            Symbol = "WAAS"
                        },
                        new
                        {
                            Id = 19,
                            Balance = 79821.970000000001,
                            Industry = "Specialty Chemicals",
                            Name = "Hawkins, Inc.",
                            Sector = "Consumer Durables",
                            Symbol = "HWKN"
                        },
                        new
                        {
                            Id = 20,
                            Balance = 22480.360000000001,
                            Industry = "n/a",
                            Name = "PennantPark Floating Rate Capital Ltd.",
                            Sector = "n/a",
                            Symbol = "PFLT"
                        },
                        new
                        {
                            Id = 21,
                            Balance = 64379.199999999997,
                            Industry = "Medical/Dental Instruments",
                            Name = "Alliqua BioMedical, Inc.",
                            Sector = "Health Care",
                            Symbol = "ALQA"
                        },
                        new
                        {
                            Id = 22,
                            Balance = 29351.200000000001,
                            Industry = "Apparel",
                            Name = "V.F. Corporation",
                            Sector = "Consumer Non-Durables",
                            Symbol = "VFC"
                        },
                        new
                        {
                            Id = 23,
                            Balance = 78091.149999999994,
                            Industry = "n/a",
                            Name = "Drive Shack Inc.",
                            Sector = "n/a",
                            Symbol = "DS^D"
                        },
                        new
                        {
                            Id = 24,
                            Balance = 95637.649999999994,
                            Industry = "Computer Software: Programming, Data Processing",
                            Name = "GDS Holdings Limited",
                            Sector = "Technology",
                            Symbol = "GDS"
                        },
                        new
                        {
                            Id = 25,
                            Balance = 75840.470000000001,
                            Industry = "Major Pharmaceuticals",
                            Name = "Seres Therapeutics, Inc.",
                            Sector = "Health Care",
                            Symbol = "MCRB"
                        },
                        new
                        {
                            Id = 26,
                            Balance = 57641.580000000002,
                            Industry = "Major Banks",
                            Name = "South State Corporation",
                            Sector = "Finance",
                            Symbol = "SSB"
                        },
                        new
                        {
                            Id = 27,
                            Balance = 12908.59,
                            Industry = "Real Estate Investment Trusts",
                            Name = "FelCor Lodging Trust Incorporated",
                            Sector = "Consumer Services",
                            Symbol = "FCH"
                        },
                        new
                        {
                            Id = 28,
                            Balance = 52723.690000000002,
                            Industry = "Metal Fabrications",
                            Name = "Proto Labs, Inc.",
                            Sector = "Capital Goods",
                            Symbol = "PRLB"
                        },
                        new
                        {
                            Id = 29,
                            Balance = 35791.330000000002,
                            Industry = "Textiles",
                            Name = "Crown Crafts, Inc.",
                            Sector = "Basic Industries",
                            Symbol = "CRWS"
                        },
                        new
                        {
                            Id = 30,
                            Balance = 23749.580000000002,
                            Industry = "Hotels/Resorts",
                            Name = "Peak Resorts, Inc.",
                            Sector = "Consumer Services",
                            Symbol = "SKIS"
                        },
                        new
                        {
                            Id = 31,
                            Balance = 51499.769999999997,
                            Industry = "Hotels/Resorts",
                            Name = "China Lodging Group, Limited",
                            Sector = "Consumer Services",
                            Symbol = "HTHT"
                        },
                        new
                        {
                            Id = 32,
                            Balance = 81785.889999999999,
                            Industry = "Other Specialty Stores",
                            Name = "Big 5 Sporting Goods Corporation",
                            Sector = "Consumer Services",
                            Symbol = "BGFV"
                        },
                        new
                        {
                            Id = 33,
                            Balance = 11477.49,
                            Industry = "Real Estate Investment Trusts",
                            Name = "Pennsylvania Real Estate Investment Trust",
                            Sector = "Consumer Services",
                            Symbol = "PEI"
                        },
                        new
                        {
                            Id = 34,
                            Balance = 89203.630000000005,
                            Industry = "Clothing/Shoe/Accessory Stores",
                            Name = "Boot Barn Holdings, Inc.",
                            Sector = "Consumer Services",
                            Symbol = "BOOT"
                        },
                        new
                        {
                            Id = 35,
                            Balance = 38603.370000000003,
                            Industry = "Oil & Gas Production",
                            Name = "Vaalco Energy Inc",
                            Sector = "Energy",
                            Symbol = "EGY"
                        },
                        new
                        {
                            Id = 36,
                            Balance = 5802.3999999999996,
                            Industry = "Major Pharmaceuticals",
                            Name = "Albireo Pharma, Inc.",
                            Sector = "Health Care",
                            Symbol = "ALBO"
                        },
                        new
                        {
                            Id = 37,
                            Balance = 10248.780000000001,
                            Industry = "n/a",
                            Name = "Tsakos Energy Navigation Ltd",
                            Sector = "n/a",
                            Symbol = "TNP^C"
                        },
                        new
                        {
                            Id = 38,
                            Balance = 64759.139999999999,
                            Industry = "Electronic Components",
                            Name = "Western Digital Corporation",
                            Sector = "Technology",
                            Symbol = "WDC"
                        },
                        new
                        {
                            Id = 39,
                            Balance = 6498.5799999999999,
                            Industry = "Electric Utilities: Central",
                            Name = "Vistra Energy Corp.",
                            Sector = "Public Utilities",
                            Symbol = "VST"
                        },
                        new
                        {
                            Id = 40,
                            Balance = 98211.899999999994,
                            Industry = "n/a",
                            Name = "Washington Prime Group Inc.",
                            Sector = "n/a",
                            Symbol = "WPG^H"
                        },
                        new
                        {
                            Id = 41,
                            Balance = 14916.440000000001,
                            Industry = "Medical/Dental Instruments",
                            Name = "Antares Pharma, Inc.",
                            Sector = "Health Care",
                            Symbol = "ATRS"
                        },
                        new
                        {
                            Id = 42,
                            Balance = 20345.330000000002,
                            Industry = "EDP Services",
                            Name = "MINDBODY, Inc.",
                            Sector = "Technology",
                            Symbol = "MB"
                        },
                        new
                        {
                            Id = 43,
                            Balance = 48828.239999999998,
                            Industry = "Semiconductors",
                            Name = "Intel Corporation",
                            Sector = "Technology",
                            Symbol = "INTC"
                        },
                        new
                        {
                            Id = 44,
                            Balance = 22197.130000000001,
                            Industry = "n/a",
                            Name = "BlackRock Investment Quality Municipal Trust Inc. (The)",
                            Sector = "n/a",
                            Symbol = "BKN"
                        },
                        new
                        {
                            Id = 45,
                            Balance = 90814.039999999994,
                            Industry = "Oil & Gas Production",
                            Name = "Harmony Merger Corp.",
                            Sector = "Public Utilities",
                            Symbol = "HRMNW"
                        },
                        new
                        {
                            Id = 46,
                            Balance = 5035.7799999999997,
                            Industry = "Major Pharmaceuticals",
                            Name = "Cellectar Biosciences, Inc.",
                            Sector = "Health Care",
                            Symbol = "CLRB"
                        },
                        new
                        {
                            Id = 47,
                            Balance = 67233.789999999994,
                            Industry = "EDP Services",
                            Name = "Park City Group, Inc.",
                            Sector = "Technology",
                            Symbol = "PCYG"
                        },
                        new
                        {
                            Id = 48,
                            Balance = 59289.510000000002,
                            Industry = "Oil Refining/Marketing",
                            Name = "Macquarie Infrastructure Company",
                            Sector = "Energy",
                            Symbol = "MIC"
                        },
                        new
                        {
                            Id = 49,
                            Balance = 71891.350000000006,
                            Industry = "Semiconductors",
                            Name = "MaxLinear, Inc",
                            Sector = "Technology",
                            Symbol = "MXL"
                        },
                        new
                        {
                            Id = 50,
                            Balance = 22161.279999999999,
                            Industry = "Oil & Gas Production",
                            Name = "Hugoton Royalty Trust",
                            Sector = "Energy",
                            Symbol = "HGT"
                        },
                        new
                        {
                            Id = 51,
                            Balance = 83215.210000000006,
                            Industry = "Major Banks",
                            Name = "Pathfinder Bancorp, Inc.",
                            Sector = "Finance",
                            Symbol = "PBHC"
                        },
                        new
                        {
                            Id = 52,
                            Balance = 64260.57,
                            Industry = "Home Furnishings",
                            Name = "Leggett & Platt, Incorporated",
                            Sector = "Consumer Durables",
                            Symbol = "LEG"
                        },
                        new
                        {
                            Id = 53,
                            Balance = 63801.889999999999,
                            Industry = "Apparel",
                            Name = "Kate Spade & Company",
                            Sector = "Consumer Non-Durables",
                            Symbol = "KATE"
                        },
                        new
                        {
                            Id = 54,
                            Balance = 3350.5100000000002,
                            Industry = "n/a",
                            Name = "Protective Life Corporation",
                            Sector = "n/a",
                            Symbol = "PL^E"
                        },
                        new
                        {
                            Id = 55,
                            Balance = 7597.96,
                            Industry = "Department/Specialty Retail Stores",
                            Name = "Cencosud S.A.",
                            Sector = "Consumer Services",
                            Symbol = "CNCO"
                        },
                        new
                        {
                            Id = 56,
                            Balance = 6098.8699999999999,
                            Industry = "Savings Institutions",
                            Name = "Magyar Bancorp, Inc.",
                            Sector = "Finance",
                            Symbol = "MGYR"
                        },
                        new
                        {
                            Id = 57,
                            Balance = 77505.589999999997,
                            Industry = "Major Pharmaceuticals",
                            Name = "DelMar Pharmaceuticals, Inc.",
                            Sector = "Health Care",
                            Symbol = "DMPI"
                        },
                        new
                        {
                            Id = 58,
                            Balance = 3428.3499999999999,
                            Industry = "n/a",
                            Name = "First Trust Small Cap Core AlphaDEX Fund",
                            Sector = "n/a",
                            Symbol = "FYX"
                        },
                        new
                        {
                            Id = 59,
                            Balance = 73733.929999999993,
                            Industry = "n/a",
                            Name = "China TechFaith Wireless Communication Technology Limited",
                            Sector = "n/a",
                            Symbol = "CNTF"
                        },
                        new
                        {
                            Id = 60,
                            Balance = 51952.18,
                            Industry = "Oil & Gas Production",
                            Name = "Canadian Natural Resources Limited",
                            Sector = "Energy",
                            Symbol = "CNQ"
                        },
                        new
                        {
                            Id = 61,
                            Balance = 41505.230000000003,
                            Industry = "Medical/Dental Instruments",
                            Name = "Glaukos Corporation",
                            Sector = "Health Care",
                            Symbol = "GKOS"
                        },
                        new
                        {
                            Id = 62,
                            Balance = 78836.589999999997,
                            Industry = "n/a",
                            Name = "Dreyfus Municipal Bond Infrastructure Fund, Inc.",
                            Sector = "n/a",
                            Symbol = "DMB"
                        },
                        new
                        {
                            Id = 63,
                            Balance = 31240.139999999999,
                            Industry = "Aerospace",
                            Name = "Grupo Aeroportuario del Sureste, S.A. de C.V.",
                            Sector = "Transportation",
                            Symbol = "ASR"
                        },
                        new
                        {
                            Id = 64,
                            Balance = 59982.029999999999,
                            Industry = "Consumer Electronics/Appliances",
                            Name = "iRobot Corporation",
                            Sector = "Consumer Durables",
                            Symbol = "IRBT"
                        },
                        new
                        {
                            Id = 65,
                            Balance = 62750.650000000001,
                            Industry = "Medical Specialities",
                            Name = "UnitedHealth Group Incorporated",
                            Sector = "Health Care",
                            Symbol = "UNH"
                        },
                        new
                        {
                            Id = 66,
                            Balance = 64337.139999999999,
                            Industry = "Computer Software: Programming, Data Processing",
                            Name = "Sabre Corporation",
                            Sector = "Technology",
                            Symbol = "SABR"
                        },
                        new
                        {
                            Id = 67,
                            Balance = 91239.970000000001,
                            Industry = "Beverages (Production/Distribution)",
                            Name = "Willamette Valley Vineyards, Inc.",
                            Sector = "Consumer Non-Durables",
                            Symbol = "WVVI"
                        },
                        new
                        {
                            Id = 68,
                            Balance = 55349.68,
                            Industry = "Other Specialty Stores",
                            Name = "ZAGG Inc",
                            Sector = "Consumer Services",
                            Symbol = "ZAGG"
                        },
                        new
                        {
                            Id = 69,
                            Balance = 93187.479999999996,
                            Industry = "Marine Transportation",
                            Name = "Navios Maritime Partners LP",
                            Sector = "Transportation",
                            Symbol = "NMM"
                        },
                        new
                        {
                            Id = 70,
                            Balance = 11844.24,
                            Industry = "Aerospace",
                            Name = "Grupo Aeroportuario del Centro Norte S.A.B. de C.V.",
                            Sector = "Transportation",
                            Symbol = "OMAB"
                        },
                        new
                        {
                            Id = 71,
                            Balance = 87019.610000000001,
                            Industry = "n/a",
                            Name = "Public Storage",
                            Sector = "n/a",
                            Symbol = "PSA^Z"
                        },
                        new
                        {
                            Id = 72,
                            Balance = 66098.820000000007,
                            Industry = "n/a",
                            Name = "Blackrock Core Bond Trust",
                            Sector = "n/a",
                            Symbol = "BHK"
                        },
                        new
                        {
                            Id = 73,
                            Balance = 57311.290000000001,
                            Industry = "Biotechnology: Electromedical & Electrotherapeutic Apparatus",
                            Name = "The Spectranetics Corporation",
                            Sector = "Health Care",
                            Symbol = "SPNC"
                        },
                        new
                        {
                            Id = 74,
                            Balance = 92281.460000000006,
                            Industry = "Hotels/Resorts",
                            Name = "MGM Resorts International",
                            Sector = "Consumer Services",
                            Symbol = "MGM"
                        },
                        new
                        {
                            Id = 75,
                            Balance = 84788.130000000005,
                            Industry = "n/a",
                            Name = "Vanguard Short-Term Government ETF",
                            Sector = "n/a",
                            Symbol = "VGSH"
                        },
                        new
                        {
                            Id = 76,
                            Balance = 30063.700000000001,
                            Industry = "Major Banks",
                            Name = "Texas Capital Bancshares, Inc.",
                            Sector = "Finance",
                            Symbol = "TCBIP"
                        },
                        new
                        {
                            Id = 77,
                            Balance = 16803.580000000002,
                            Industry = "Specialty Foods",
                            Name = "J & J Snack Foods Corp.",
                            Sector = "Consumer Non-Durables",
                            Symbol = "JJSF"
                        },
                        new
                        {
                            Id = 78,
                            Balance = 51587.360000000001,
                            Industry = "Advertising",
                            Name = "WPP plc",
                            Sector = "Technology",
                            Symbol = "WPPGY"
                        },
                        new
                        {
                            Id = 79,
                            Balance = 45519.290000000001,
                            Industry = "Industrial Machinery/Components",
                            Name = "Key Technology, Inc.",
                            Sector = "Technology",
                            Symbol = "KTEC"
                        },
                        new
                        {
                            Id = 80,
                            Balance = 15341.25,
                            Industry = "n/a",
                            Name = "Sophiris Bio, Inc.",
                            Sector = "n/a",
                            Symbol = "SPHS"
                        },
                        new
                        {
                            Id = 81,
                            Balance = 35990.809999999998,
                            Industry = "n/a",
                            Name = "PartnerRe Ltd.",
                            Sector = "n/a",
                            Symbol = "PRE^G"
                        },
                        new
                        {
                            Id = 82,
                            Balance = 88537.059999999998,
                            Industry = "Oilfield Services/Equipment",
                            Name = "CSI Compressco LP",
                            Sector = "Energy",
                            Symbol = "CCLP"
                        },
                        new
                        {
                            Id = 83,
                            Balance = 31509.09,
                            Industry = "Advertising",
                            Name = "Criteo S.A.",
                            Sector = "Technology",
                            Symbol = "CRTO"
                        },
                        new
                        {
                            Id = 84,
                            Balance = 37413.410000000003,
                            Industry = "Biotechnology: Biological Products (No Diagnostic Substances)",
                            Name = "Aviragen Therapeutics, Inc.",
                            Sector = "Health Care",
                            Symbol = "AVIR"
                        },
                        new
                        {
                            Id = 85,
                            Balance = 28476.529999999999,
                            Industry = "n/a",
                            Name = "State Street Corporation",
                            Sector = "n/a",
                            Symbol = "STT^E"
                        },
                        new
                        {
                            Id = 86,
                            Balance = 54783.059999999998,
                            Industry = "Major Banks",
                            Name = "Old Point Financial Corporation",
                            Sector = "Finance",
                            Symbol = "OPOF"
                        },
                        new
                        {
                            Id = 87,
                            Balance = 74553.880000000005,
                            Industry = "n/a",
                            Name = "iShares MSCI ACWI ex US Index Fund",
                            Sector = "n/a",
                            Symbol = "ACWX"
                        },
                        new
                        {
                            Id = 88,
                            Balance = 82628.449999999997,
                            Industry = "Biotechnology: Commercial Physical & Biological Resarch",
                            Name = "Exelixis, Inc.",
                            Sector = "Health Care",
                            Symbol = "EXEL"
                        },
                        new
                        {
                            Id = 89,
                            Balance = 58492.610000000001,
                            Industry = "Steel/Iron Ore",
                            Name = "Ternium S.A.",
                            Sector = "Basic Industries",
                            Symbol = "TX"
                        },
                        new
                        {
                            Id = 90,
                            Balance = 87167.309999999998,
                            Industry = "Industrial Machinery/Components",
                            Name = "CBAK Energy Technology, Inc.",
                            Sector = "Miscellaneous",
                            Symbol = "CBAK"
                        },
                        new
                        {
                            Id = 91,
                            Balance = 74861.440000000002,
                            Industry = "Major Pharmaceuticals",
                            Name = "Soligenix, Inc.",
                            Sector = "Health Care",
                            Symbol = "SNGX"
                        },
                        new
                        {
                            Id = 92,
                            Balance = 34085.300000000003,
                            Industry = "Major Pharmaceuticals",
                            Name = "Novo Nordisk A/S",
                            Sector = "Health Care",
                            Symbol = "NVO"
                        },
                        new
                        {
                            Id = 93,
                            Balance = 90172.300000000003,
                            Industry = "Precious Metals",
                            Name = "Uranium Resources, Inc.",
                            Sector = "Basic Industries",
                            Symbol = "URRE"
                        },
                        new
                        {
                            Id = 94,
                            Balance = 43757.610000000001,
                            Industry = "n/a",
                            Name = "Second Sight Medical Products, Inc.",
                            Sector = "n/a",
                            Symbol = "EYES"
                        },
                        new
                        {
                            Id = 95,
                            Balance = 82323.929999999993,
                            Industry = "Major Pharmaceuticals",
                            Name = "PhaseRx, Inc.",
                            Sector = "Health Care",
                            Symbol = "PZRX"
                        },
                        new
                        {
                            Id = 96,
                            Balance = 71047.130000000005,
                            Industry = "Radio And Television Broadcasting And Communications Equipment",
                            Name = "Pointer Telocation Ltd.",
                            Sector = "Technology",
                            Symbol = "PNTR"
                        },
                        new
                        {
                            Id = 97,
                            Balance = 35785.669999999998,
                            Industry = "Major Pharmaceuticals",
                            Name = "AMAG Pharmaceuticals, Inc.",
                            Sector = "Health Care",
                            Symbol = "AMAG"
                        },
                        new
                        {
                            Id = 98,
                            Balance = 31341.639999999999,
                            Industry = "Marine Transportation",
                            Name = "Scorpio Tankers Inc.",
                            Sector = "Transportation",
                            Symbol = "SBNA"
                        },
                        new
                        {
                            Id = 99,
                            Balance = 2178.9299999999998,
                            Industry = "n/a",
                            Name = "PowerShares DWA Consumer Staples Momentum Portfolio",
                            Sector = "n/a",
                            Symbol = "PSL"
                        },
                        new
                        {
                            Id = 100,
                            Balance = 92176.679999999993,
                            Industry = "Accident &Health Insurance",
                            Name = "Assurant, Inc.",
                            Sector = "Finance",
                            Symbol = "AIZ"
                        },
                        new
                        {
                            Id = 101,
                            Balance = 54742.529999999999,
                            Industry = "Industrial Specialties",
                            Name = "Inogen, Inc",
                            Sector = "Health Care",
                            Symbol = "INGN"
                        },
                        new
                        {
                            Id = 102,
                            Balance = 29819.959999999999,
                            Industry = "Electrical Products",
                            Name = "Itron, Inc.",
                            Sector = "Capital Goods",
                            Symbol = "ITRI"
                        },
                        new
                        {
                            Id = 103,
                            Balance = 27661.119999999999,
                            Industry = "Computer Communications Equipment",
                            Name = "A10 Networks, Inc.",
                            Sector = "Technology",
                            Symbol = "ATEN"
                        },
                        new
                        {
                            Id = 104,
                            Balance = 78015.050000000003,
                            Industry = "Oil Refining/Marketing",
                            Name = "Hunter Maritime Acquisition Corp.",
                            Sector = "Transportation",
                            Symbol = "HUNT"
                        },
                        new
                        {
                            Id = 105,
                            Balance = 54286.529999999999,
                            Industry = "Major Banks",
                            Name = "Colony Bankcorp, Inc.",
                            Sector = "Finance",
                            Symbol = "CBAN"
                        },
                        new
                        {
                            Id = 106,
                            Balance = 53985.800000000003,
                            Industry = "Oil Refining/Marketing",
                            Name = "C.H. Robinson Worldwide, Inc.",
                            Sector = "Transportation",
                            Symbol = "CHRW"
                        },
                        new
                        {
                            Id = 107,
                            Balance = 74587.330000000002,
                            Industry = "Finance: Consumer Services",
                            Name = "Enova International, Inc.",
                            Sector = "Finance",
                            Symbol = "ENVA"
                        },
                        new
                        {
                            Id = 108,
                            Balance = 11486.77,
                            Industry = "Radio And Television Broadcasting And Communications Equipment",
                            Name = "QUALCOMM Incorporated",
                            Sector = "Technology",
                            Symbol = "QCOM"
                        },
                        new
                        {
                            Id = 109,
                            Balance = 62602.779999999999,
                            Industry = "Medical/Dental Instruments",
                            Name = "Globus Medical, Inc.",
                            Sector = "Health Care",
                            Symbol = "GMED"
                        },
                        new
                        {
                            Id = 110,
                            Balance = 2535.1100000000001,
                            Industry = "n/a",
                            Name = "First Trust Nasdaq Pharmaceuticals ETF",
                            Sector = "n/a",
                            Symbol = "FTXH"
                        });
                });

            modelBuilder.Entity("EFCore.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Story");
                });

            modelBuilder.Entity("EFCore.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("StoryTag", b =>
                {
                    b.Property<int>("StoriesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsTagId")
                        .HasColumnType("int");

                    b.HasKey("StoriesId", "TagsTagId");

                    b.HasIndex("TagsTagId");

                    b.ToTable("StoryTag");
                });

            modelBuilder.Entity("EFCore.Models.BlogImage", b =>
                {
                    b.HasOne("EFCore.Models.Blog", "Blog")
                        .WithOne("BlogImage")
                        .HasForeignKey("EFCore.Models.BlogImage", "BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("EFCore.Models.Post", b =>
                {
                    b.HasOne("EFCore.Models.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("StoryTag", b =>
                {
                    b.HasOne("EFCore.Models.Story", null)
                        .WithMany()
                        .HasForeignKey("StoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.Models.Blog", b =>
                {
                    b.Navigation("BlogImage")
                        .IsRequired();

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
